import { GroupPack } from './KindredLogic';

export const GROUP_PACKS: GroupPack[] = [
  { groups: [{ label: "Fruits", words: ["APPLE", "GRAPE", "PEACH", "PLUM"] }, { label: "Flowers", words: ["ROSE", "DAISY", "TULIP", "LILY"] }, { label: "Trees", words: ["OAK", "PINE", "MAPLE", "WILLOW"] }, { label: "Vegetables", words: ["CARROT", "ONION", "POTATO", "BEAN"] }] },
  { groups: [{ label: "Baby animals", words: ["KITTEN", "PUPPY", "LAMB", "CHICK"] }, { label: "Breakfast foods", words: ["TOAST", "EGG", "PANCAKE", "CEREAL"] }, { label: "Weather", words: ["RAIN", "SNOW", "WIND", "FROST"] }, { label: "Kitchen items", words: ["PAN", "BOWL", "SPOON", "KETTLE"] }] },
  { groups: [{ label: "Hot drinks", words: ["TEA", "COFFEE", "COCOA", "CIDER"] }, { label: "Birds", words: ["ROBIN", "EAGLE", "CROW", "DOVE"] }, { label: "Colors", words: ["RED", "BLUE", "GREEN", "GOLD"] }, { label: "Body parts", words: ["PALM", "NAIL", "BACK", "SOLE"] }] },
  { groups: [{ label: "Musical instruments", words: ["DRUM", "FLUTE", "HARP", "BELL"] }, { label: "Sea creatures", words: ["CRAB", "WHALE", "SHARK", "SQUID"] }, { label: "Things that spin", words: ["WHEEL", "TOP", "FAN", "COIN"] }, { label: "Fabrics", words: ["SILK", "WOOL", "COTTON", "LINEN"] }] },
  { groups: [{ label: "Things in the sky", words: ["STAR", "MOON", "CLOUD", "SUN"] }, { label: "Farm animals", words: ["COW", "PIG", "SHEEP", "HEN"] }, { label: "Grains", words: ["RYE", "WHEAT", "OAT", "CORN"] }, { label: "At the beach", words: ["SAND", "WAVE", "SHELL", "TOWEL"] }] },
  { groups: [{ label: "Insects", words: ["ANT", "BEE", "FLY", "MOTH"] }, { label: "Tools", words: ["SAW", "DRILL", "HAMMER", "WRENCH"] }, { label: "Desserts", words: ["CAKE", "PIE", "TART", "FUDGE"] }, { label: "Ball sports", words: ["GOLF", "TENNIS", "RUGBY", "CRICKET"] }] },
  { groups: [{ label: "Playing card ranks", words: ["ACE", "KING", "QUEEN", "JACK"] }, { label: "Gemstones", words: ["RUBY", "PEARL", "JADE", "OPAL"] }, { label: "Metals", words: ["IRON", "TIN", "LEAD", "ZINC"] }, { label: "Containers", words: ["BAG", "BOX", "JAR", "CAN"] }] },
  { groups: [{ label: "Dances", words: ["WALTZ", "SALSA", "TANGO", "SWING"] }, { label: "Furniture", words: ["CHAIR", "TABLE", "DESK", "SHELF"] }, { label: "Emotions", words: ["JOY", "FEAR", "HOPE", "LOVE"] }, { label: "Fruits", words: ["MANGO", "LEMON", "CHERRY", "MELON"] }] },
  { groups: [{ label: "Clothing", words: ["SHIRT", "COAT", "BELT", "BOOT"] }, { label: "Fairy tale characters", words: ["WITCH", "WOLF", "PRINCE", "GIANT"] }, { label: "Round things", words: ["BALL", "RING", "GLOBE", "CLOCK"] }, { label: "Things in a garden", words: ["FENCE", "SHED", "BENCH", "HOSE"] }] },
  { groups: [{ label: "School supplies", words: ["CHALK", "PEN", "RULER", "ERASER"] }, { label: "Things that melt", words: ["ICE", "WAX", "BUTTER", "CHEESE"] }, { label: "Reptiles", words: ["SNAKE", "LIZARD", "TURTLE", "GECKO"] }, { label: "Vegetables", words: ["PEA", "LEEK", "BEET", "KALE"] }] },
  { groups: [{ label: "Vehicles", words: ["CAR", "BUS", "BOAT", "TRAM"] }, { label: "Planets", words: ["MARS", "VENUS", "PLUTO", "SATURN"] }, { label: "Sharp things", words: ["BLADE", "THORN", "NEEDLE", "CLAW"] }, { label: "Types of hat", words: ["CAP", "BERET", "CROWN", "HOOD"] }] },
  { groups: [{ label: "Spices", words: ["PEPPER", "CLOVE", "SAGE", "CUMIN"] }, { label: "Fish", words: ["TROUT", "SALMON", "BASS", "TUNA"] }, { label: "Parts of a book", words: ["SPINE", "COVER", "PAGE", "TITLE"] }, { label: "Board games", words: ["CHESS", "RISK", "CLUE", "LIFE"] }] },
  { groups: [{ label: "Animal sounds", words: ["BARK", "ROAR", "PURR", "HISS"] }, { label: "Toys", words: ["DOLL", "KITE", "BLOCK", "SLED"] }, { label: "Things in a park", words: ["SLIDE", "POND", "PATH", "GATE"] }, { label: "Ocean things", words: ["CORAL", "TIDE", "REEF", "KELP"] }] },
  { groups: [{ label: "Zoo animals", words: ["LION", "TIGER", "BEAR", "ZEBRA"] }, { label: "Types of bread", words: ["ROLL", "LOAF", "WRAP", "BUN"] }, { label: "Things that glow", words: ["EMBER", "FLAME", "TORCH", "NEON"] }, { label: "In a bathroom", words: ["SOAP", "TILE", "DRAIN", "TAP"] }] },
  { groups: [{ label: "Music genres", words: ["JAZZ", "ROCK", "FOLK", "POP"] }, { label: "Weather conditions", words: ["HAZE", "SLEET", "FOG", "GUST"] }, { label: "Dog commands", words: ["SIT", "STAY", "FETCH", "HEEL"] }, { label: "Breakfast drinks", words: ["JUICE", "MILK", "WATER", "SHAKE"] }] },
  { groups: [{ label: "Rooms in a house", words: ["ATTIC", "HALL", "PORCH", "DEN"] }, { label: "Things with wings", words: ["PLANE", "WASP", "BAT", "SWAN"] }, { label: "Building materials", words: ["BRICK", "GLASS", "CLAY", "STONE"] }, { label: "Fruits", words: ["FIG", "LIME", "PEAR", "DATE"] }] },
  { groups: [{ label: "Camping things", words: ["TENT", "FIRE", "ROPE", "MAP"] }, { label: "Shapes", words: ["CUBE", "CONE", "OVAL", "ARCH"] }, { label: "Snacks", words: ["CHIP", "NUT", "DIP", "CRISP"] }, { label: "Magic show things", words: ["WAND", "CAPE", "TRICK", "HAT"] }] },
  { groups: [{ label: "Parts of a ship", words: ["MAST", "SAIL", "HULL", "DECK"] }, { label: "Office supplies", words: ["STAMP", "CLIP", "FILE", "TAPE"] }, { label: "Parts of a tree", words: ["ROOT", "TRUNK", "BRANCH", "LEAF"] }, { label: "Feelings", words: ["PRIDE", "SHAME", "GRIEF", "BLISS"] }] },
  { groups: [{ label: "Night things", words: ["OWL", "DREAM", "LAMP", "PILLOW"] }, { label: "Sudden sounds", words: ["BUZZ", "CLICK", "BANG", "THUD"] }, { label: "Paper things", words: ["NOTE", "CARD", "FOLD", "SHEET"] }, { label: "Swimming pool things", words: ["LANE", "FLOAT", "DIVE", "SPLASH"] }] },
  { groups: [{ label: "Things in a castle", words: ["MOAT", "TOWER", "SWORD", "FLAG"] }, { label: "Sweets", words: ["CANDY", "TOFFEE", "GUM", "MINT"] }, { label: "Things that are fast", words: ["BOLT", "FLASH", "DART", "SPRINT"] }, { label: "Art supplies", words: ["BRUSH", "PAINT", "INK", "EASEL"] }] },
];
