const quoteDatabase: string[] = [
  "A good bench in the shade is never empty for long",
  "Some paths on campus only make sense after you walk them",
  "The library smells like old paper and quiet afternoons",
  "Morning tea tastes better when you share it with friends",
  "Every building on campus has a story if you listen",
  "Old stairs have more character than new elevators",
  "Sitting under a tree with nothing to do is a fine thing",
  "Lunch is always better when eaten on the steps outside",
  "Nobody plans the best conversations they just happen",
  "Rain on the tin roof of the canteen sounds like home",
  "Walking slow is the only way to notice small things",
  "That one corner where everyone sits but nobody owns",
  "If the walls could talk they would tell you to rest",
  "Chai from the corner shop fixes most things before noon",
  "Friends who study together often forget to study at all",
  "You can learn a lot about a place by sitting still in it",
  "Good mornings start with warm food and familiar faces",
  "Between classes is when campus comes alive",
  "Dusty corridors have their own kind of warmth",
  "Half the fun of a shared meal is the argument over what to eat",
  "Quiet places are hard to find but easy to remember",
  "One empty classroom can hold a hundred good ideas",
  "Trees on campus have seen more exams than any student",
  "Staying back after hours is when you find the best spots",
  "Borrowed notes always come with small drawings in the margins",
  "Parked bikes near the entrance tell you who came early",
  "Warm sunlight on an old wall is enough to make you stop",
  "Most students have a favorite spot they never tell anyone",
  "Sharing a table with a stranger can turn into a friendship",
  "Late nights in the studio make everything feel important",
  "Waiting for the bus is better when someone makes you laugh",
  "Even a plain wall looks nice when the light hits it right",
  "Nothing beats finding a cool spot on a hot afternoon",
  "Weekend campus is a different world from Monday campus",
  "An open door at the end of a long hallway feels like a gift",
  "Footsteps echo more in the evening when the crowd is gone",
  "Just because a place is old does not mean it has nothing left",
  "Corridors carry the sound of laughter long after everyone leaves",
  "Places remember how people used them even when people forget",
  "Under the big tree by the gate is where stories begin",
  "Every tree grew from a seed that had no plan at all",
  "Rain does not ask if you are ready before it falls",
  "Morning light touches the world without making a sound",
  "Birds sing because the morning feels too good to waste",
  "Small flowers grow between the cracks without any help",
  "The sky changes color slowly and nobody seems to mind",
  "A garden does not rush and still everything blooms",
  "Clouds move across the sky like slow quiet visitors",
  "Leaves turn gold and red when the season asks them to",
  "Wind carries seeds to places no one has ever seen",
  "Sunlight finds its way through even the thickest forest",
  "Quiet evenings bring the best kind of peace to a tired day",
  "One butterfly can make a whole garden feel alive",
  "Stars appear one by one like old friends coming back",
  "Green is the first color that the earth always chooses",
  "Frogs begin to sing the moment the first raindrop falls",
  "Tall trees once were tiny seeds that nobody noticed",
  "Honey bees visit a hundred flowers before noon each day",
  "Deep in the forest the air smells like wet earth and moss",
  "Night brings a cool breeze that the whole town enjoys",
  "Puddles on the road reflect the sky after a good rain",
  "Under the mango tree it is always a few degrees cooler",
  "You can learn a lot just by watching how rivers move",
  "Gentle winds carry the smell of jasmine across the street",
  "Rivers never stop moving and they never seem tired",
  "Warm afternoons are best spent sitting under a big tree",
  "Dewdrops on a leaf look like tiny glass beads in the sun",
  "Sparrows know every corner of the town better than we do",
  "If you sit still long enough a bird will come say hello",
  "After the storm the whole world looks freshly washed",
  "Fireflies turn an ordinary night into something special",
  "Nothing is louder than a garden full of crickets at night",
  "Just before sunrise the air has a sweetness to it",
  "Coconut trees bend with the wind but they never break",
  "Petals fall gently and the ground becomes a soft carpet",
  "Watching the sunset is free and it never gets old",
  "Roots grow deep and quiet where nobody is looking",
  "Ants carry things ten times their size without complaining",
  "Sometimes the best view is just outside your own window",
  "Old banyan trees have seen more seasons than we can count"
];

export default quoteDatabase;
